config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/madgeek-arc/eosc-node-endpoint:
      branch: main
      repo: https://github.com/madgeek-arc/eosc-node-endpoint.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/madgeek-arc/eosc-node-endpoint git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-rose-abyssinian.sh
        container: qc.acc_scaly-white-audemer
  QC.Doc:
    repos:
      github.com/madgeek-arc/eosc-node-endpoint find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-emerald-mongoose.sh
        container: qc.doc_wheezy-aquamarine-avocet
      github.com/madgeek-arc/eosc-node-endpoint git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-green-indri.sh
        container: qc.doc_hasty-salmon-weasel
      github.com/madgeek-arc/eosc-node-endpoint markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-goldenrod-shrew.sh
        container: qc.doc_geeky-ecru-cougar
  QC.Lic:
    repos:
      github.com/madgeek-arc/eosc-node-endpoint licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-aqua-snail.sh
        container: qc.lic_bumpy-sangria-centipede
  QC.Sty:
    repos:
      github.com/madgeek-arc/eosc-node-endpoint checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-rose-chamois.sh
        container: qc.sty_geeky-vermilion-binturong
      github.com/madgeek-arc/eosc-node-endpoint jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-sangria-fly.sh
        container: qc.sty_paltry-taupe-crane
  QC.Ver:
    repos:
      github.com/madgeek-arc/eosc-node-endpoint get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-plum-sponge.sh
        container: qc.ver_tacky-green-anteater
timeout: 5400
